name: Docker build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the code 
    - uses: actions/checkout@v3
    - run: docker build -t back .
      working-directory: back
    - run : docker login -u ${{ secret.DOCKER_USER }}  -p ${{ secret.DOCKER_SECRET }} ghcr.io
